"""Geometry, fonts and grid positions of the Tk desktop window."""

from __future__ import annotations

from typing import Final

# One wheel notch moves three of these steps, matching the Windows default.
PAGE_SCROLL_STEP_PIXELS: Final = 20
WHEEL_STEPS_PER_NOTCH: Final = 3
# A dead band keeps a label's wrap width from oscillating by a pixel.
WRAP_WIDTH_DEAD_BAND_PIXELS: Final = 6
# Reserved gutters keep the layout still while the markers appear and vanish.
MODIFIED_MARKER_WIDTH_PIXELS: Final = 3
MODIFIED_MARKER_COLUMN_MIN_PIXELS: Final = 12
RESET_BUTTON_COLUMN_MIN_PIXELS: Final = 54
RESET_BUTTON_INTERNAL_PADDING_PIXELS: Final = 2
RESET_BUTTON_FONT_SIZE_POINTS: Final = 8
DESCRIPTION_INDENT_PIXELS: Final = 24
DESCRIPTION_MARGIN_PIXELS: Final = 12
DESCRIPTION_MINIMUM_WRAP_PIXELS: Final = 120
DESCRIPTION_INITIAL_WRAP_PIXELS: Final = 260
PAGE_PADDING_X_PIXELS: Final = 30
# Horizontal page padding applies on both sides.
PAGE_PADDING_SIDES: Final = 2
PAGE_CONTENT_PADDING_Y_PIXELS: Final = 24
PAGE_CAPTION_PADDING_TOP_PIXELS: Final = 3
PAGE_CAPTION_PADDING_BOTTOM_PIXELS: Final = 18
PAGE_SUBTITLE_WRAP_WIDTH_PIXELS: Final = 760
# The wraplength most body copy on a page settles into once laid out.
CONTENT_TEXT_WRAP_WIDTH_PIXELS: Final = 720
PAGE_TITLE_FONT_SIZE_POINTS: Final = 22
CARD_TITLE_FONT_SIZE_POINTS: Final = 10
BRAND_LABEL_FONT_SIZE_POINTS: Final = 20
LABELFRAME_TITLE_FONT_SIZE_POINTS: Final = 11
# Row/column layout of one setting inside its LabelFrame.
SETTING_ROW_PADDING_PIXELS: Final = 5
# Column of a setting row's reset button; the marker takes column 0 and the label with its control
# column 1.
SETTING_RESET_COLUMN_INDEX: Final = 2
SETTING_ROW_COLUMN_SPAN: Final = 2
SETTING_CONTROL_PADDING_LEFT_PIXELS: Final = 16
CHOICE_CONTROL_WIDTH_CHARACTERS: Final = 22
NUMBER_CONTROL_WIDTH_CHARACTERS: Final = 12
TEXT_CONTROL_WIDTH_CHARACTERS: Final = 25
NUMBER_DISPLAY_DECIMAL_PLACES: Final = 2
MAIN_WINDOW_MIN_WIDTH_PIXELS: Final = 900
MAIN_WINDOW_MIN_HEIGHT_PIXELS: Final = 640
DESKTOP_SIDEBAR_WIDTH_PIXELS: Final = 225
SIDEBAR_PADDING_X_PIXELS: Final = 16
SIDEBAR_PADDING_Y_PIXELS: Final = 18
SIDEBAR_ITEM_PADDING_X_PIXELS: Final = 8
SIDEBAR_BRAND_PADDING_BOTTOM_PIXELS: Final = 2
SIDEBAR_SUBTITLE_PADDING_BOTTOM_PIXELS: Final = 18
SIDEBAR_SEPARATOR_PADDING_Y_PIXELS: Final = 16
SIDEBAR_STATUS_PADDING_TOP_PIXELS: Final = 4
NAVIGATION_BUTTON_PADDING_X_PIXELS: Final = 12
NAVIGATION_BUTTON_PADDING_Y_PIXELS: Final = 8
NAVIGATION_BUTTON_SPACING_PIXELS: Final = 2
TOOLTIP_VERTICAL_GAP_PIXELS: Final = 4
TOOLTIP_PADDING_X_PIXELS: Final = 8
TOOLTIP_PADDING_Y_PIXELS: Final = 4
# The (18, 14) padding a ttk.LabelFrame section uses inside, and the margin below it before the next
# section starts.
SECTION_PADDING_X_PIXELS: Final = 18
SECTION_PADDING_Y_PIXELS: Final = 14
SECTION_BOTTOM_MARGIN_PIXELS: Final = 14
# The two spacing units the settings window lays rows and controls out on.
STANDARD_GAP_PIXELS: Final = 8
GROUP_GAP_PIXELS: Final = 10
CARD_TITLE_GAP_PIXELS: Final = 6
STATUS_LINE_GAP_PIXELS: Final = 4
# Rows 0 and 1 of every settings page hold the title and caption _new_page places; the first section
# or table of a page goes on the row below them.
PAGE_FIRST_SECTION_ROW: Final = 2
# Grid rows inside the overview status section: status title 0, layout 1, then these.
OVERVIEW_COUNT_ROW: Final = 2
OVERVIEW_LAST_ACTION_ROW: Final = 3
OVERVIEW_ERROR_ROW: Final = 4
OVERVIEW_AUTOCORRECTION_PREVIEW_ROW: Final = 5
OVERVIEW_TEST_SECTION_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
OVERVIEW_TEST_HINT_ROW: Final = 2
TEST_ENTRY_FONT_SIZE_POINTS: Final = 14
TEST_ENTRY_PADDING_TOP_PIXELS: Final = 12
TEST_ENTRY_PADDING_BOTTOM_PIXELS: Final = 2
AUTOCORRECTION_PRIMARY_COLUMN_WEIGHT: Final = 3
AUTOCORRECTION_SECONDARY_COLUMN_WEIGHT: Final = 2
AUTOCORRECTION_COLUMN_GAP_PIXELS: Final = 7
QUIRKS_COLUMN_SPAN: Final = 2
QUIRKS_TOP_MARGIN_PIXELS: Final = 14
LAYOUT_LANGUAGE_LABEL_PADDING_TOP_PIXELS: Final = 2
LAYOUT_LANGUAGE_LABEL_PADDING_BOTTOM_PIXELS: Final = 10
LAYOUTS_RU_HEADING_ROW: Final = 2
LAYOUTS_RU_VALUE_ROW: Final = 3
LAYOUTS_REFRESH_BUTTON_ROW: Final = 4
LAYOUTS_MANUAL_SWITCH_SECTION_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
MANUAL_SWITCH_NOTE_COLUMN_SPAN: Final = 2
MANUAL_SWITCH_NOTE_PADDING_TOP_PIXELS: Final = 8
APPLICATION_LIST_HEIGHT_ROWS: Final = 6
APPLICATION_LIST_COLUMN_SPAN: Final = 4
EXCLUSIONS_REMOVE_BUTTON_COLUMN: Final = 3
EXCLUSIONS_CATALOG_ROW: Final = 2
EXCLUSIONS_CATALOG_COLUMN_SPAN: Final = 2
EXCLUSIONS_REFRESH_BUTTON_COLUMN: Final = 2
EXCLUSIONS_MANUAL_ENTRY_ROW: Final = 3
EXCLUSIONS_MANUAL_ENTRY_COLUMN_SPAN: Final = 3
EXCLUSIONS_WORDS_SECTION_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
WORD_LIST_HEIGHT_ROWS: Final = 5
WORD_LIST_COLUMN_SPAN: Final = 2
HISTORY_TIME_COLUMN_WIDTH_PIXELS: Final = 165
HISTORY_WORD_COLUMN_WIDTH_PIXELS: Final = 130
HISTORY_APPLICATION_COLUMN_WIDTH_PIXELS: Final = 150
HISTORY_CONFIDENCE_COLUMN_WIDTH_PIXELS: Final = 100
HISTORY_TREE_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
UPDATES_PROGRESS_ROW: Final = 2
UPDATES_POLICY_SECTION_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
UPDATES_ACTIONS_SECTION_ROW: Final = UPDATES_POLICY_SECTION_ROW + 1
LEARNING_TREE_HEIGHT_ROWS: Final = 6
LEARNING_WORD_COLUMN_WIDTH_PIXELS: Final = 150
LEARNING_DIRECTION_COLUMN_WIDTH_PIXELS: Final = 105
LEARNING_CONFIRMATIONS_COLUMN_WIDTH_PIXELS: Final = 115
LEARNING_STATE_COLUMN_WIDTH_PIXELS: Final = 175
MAINTENANCE_DESCRIPTION_ROW: Final = 2
MAINTENANCE_LEARNING_ACTIONS_ROW: Final = 3
MAINTENANCE_CLEAR_REJECTIONS_BUTTON_COLUMN: Final = 2
MAINTENANCE_SETTINGS_SECTION_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
MAINTENANCE_DIAGNOSTICS_SECTION_ROW: Final = MAINTENANCE_SETTINGS_SECTION_ROW + 1
MAINTENANCE_LOCATIONS_SECTION_ROW: Final = MAINTENANCE_DIAGNOSTICS_SECTION_ROW + 1
DIAGNOSTICS_TEXT_HEIGHT_ROWS: Final = 15
# The licence line sits on the page below the about section.
ABOUT_LICENSE_LABEL_ROW: Final = PAGE_FIRST_SECTION_ROW + 1
# SettingSpec.maximum when a setting names none. Unused by any control today: every int/float
# setting passes its own maximum.
SETTING_SPEC_DEFAULT_MAXIMUM: Final = 100.0
