// CUDA featurizer for context-v3, part 1: characters, strings, tables, exact float helpers,
// LanguageModel.score. Every function mirrors a Python function operation for operation; the
// Python source each one follows is named above it. Built with --fmad=false: no contraction.
#pragma once
#include "ks_constants.h"   // generated by tools/context_action_cuda.py from keyswitch.constants

typedef unsigned int cp;
typedef unsigned long long u64;
typedef long long i64;

// The origins of context_model.AfterOrigin, in its order (checked by the host).
enum Origin { ORIGIN_NONE, ORIGIN_FIELD, ORIGIN_PLANNED, ORIGIN_COUNT };

#define MAXS KS_CONTEXT_ACTION_CUDA_TOKEN_CHARACTERS   // longest token a thread handles (longer rows go to the CPU path)
#define MAXCTX KS_CONTEXT_ACTION_CUDA_CONTEXT_CHARACTERS   // longest context slice

// ---- character properties (exported from Python's str methods, per BMP code point) ----
// The P_* bits come from CONTEXT_ACTION_CUDA_CHARACTER_PROPERTIES in the generated header:
// P_KNOWN (in the exported table: anything else sends the row to the CPU path), P_ALPHA (str.isalpha),
// P_DIGIT (str.isdigit), P_DECIMAL (str.isdecimal, regex \d), P_SPACE (str.isspace), P_UPPER/P_LOWER/
// P_TITLE (Py_UNICODE_ISUPPER/ISLOWER/ISTITLE), P_ALNUM (str.isalnum), P_WORD (re [^\W\d_]),
// P_CYRILLIC_NAME / P_LATIN_NAME ("CYRILLIC" / "LATIN" in unicodedata.name).

struct HashTable {           // open addressing; keys are UTF-32 strings in `pool`
    u64 hashes, offsets, lengths, values, pool, mask;
};

struct Model {
    u64 props, fold, upper;  // per code point: property bits, casefold (one code point), str.upper
    // language models per locale (0 en_US, 1 ru_RU); the profiles share the frequency tables
    HashTable freq[KS_LAYOUT_GROUP_COUNT];       // word -> index; values: frequency (i64), popularity (double)
    u64 freq_count[KS_LAYOUT_GROUP_COUNT], popularity[KS_LAYOUT_GROUP_COUNT];
    HashTable grams[KS_LAYOUT_GROUP_COUNT][KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT];   // LANGUAGE_MODEL_NGRAM_ORDERS: gram -> index into gram_log
    u64 gram_log[KS_LAYOUT_GROUP_COUNT][KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT];
    double unseen_log[KS_LAYOUT_GROUP_COUNT][KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT];
    double ngram_mean[KS_LAYOUT_GROUP_COUNT], ngram_deviation[KS_LAYOUT_GROUP_COUNT];
    HashTable bigram[KS_LAYOUT_GROUP_COUNT];     // "w1\0w2" -> index into bigram_value
    u64 bigram_value[KS_LAYOUT_GROUP_COUNT];
    HashTable hunspell[KS_LAYOUT_GROUP_COUNT];   // normalized word -> 0/1 (answers of HunspellDictionary.check)
    u64 hunspell_value[KS_LAYOUT_GROUP_COUNT];
    i64 orders[KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT];
};

__device__ __forceinline__ unsigned props(const Model* M, cp c) {
    return c < (cp)KS_CONTEXT_ACTION_CUDA_CODE_POINTS ? ((const unsigned*)M->props)[c] : 0u;
}
__device__ __forceinline__ cp casefold(const Model* M, cp c) { return ((const unsigned*)M->fold)[c]; }
__device__ __forceinline__ bool is_alpha(const Model* M, cp c) { return props(M, c) & P_ALPHA; }
__device__ __forceinline__ bool is_space(const Model* M, cp c) { return props(M, c) & P_SPACE; }
__device__ __forceinline__ bool is_digit(const Model* M, cp c) { return props(M, c) & P_DIGIT; }

// Python's min/max on two floats: the first argument unless the second is strictly smaller/larger.
__device__ __forceinline__ double py_min(double a, double b) { return b < a ? b : a; }
__device__ __forceinline__ double py_max(double a, double b) { return b > a ? b : a; }

// str.isalpha / isupper / islower / istitle as CPython implements them (unicodeobject.c).
__device__ bool str_isalpha(const Model* M, const cp* s, int n) {
    if (n == 0) return false;
    for (int i = 0; i < n; ++i) if (!(props(M, s[i]) & P_ALPHA)) return false;
    return true;
}
__device__ bool str_isupper(const Model* M, const cp* s, int n) {
    if (n == 1) return props(M, s[0]) & P_UPPER;
    bool cased = false;
    for (int i = 0; i < n; ++i) {
        unsigned p = props(M, s[i]);
        if ((p & P_LOWER) || (p & P_TITLE)) return false;
        else if (!cased && (p & P_UPPER)) cased = true;
    }
    return cased;
}
__device__ bool str_islower(const Model* M, const cp* s, int n) {
    if (n == 1) return props(M, s[0]) & P_LOWER;
    bool cased = false;
    for (int i = 0; i < n; ++i) {
        unsigned p = props(M, s[i]);
        if ((p & P_UPPER) || (p & P_TITLE)) return false;
        else if (!cased && (p & P_LOWER)) cased = true;
    }
    return cased;
}
__device__ bool str_istitle(const Model* M, const cp* s, int n) {
    if (n == 1) { unsigned p = props(M, s[0]); return (p & P_TITLE) || (p & P_UPPER); }
    bool cased = false, previous_is_cased = false;
    for (int i = 0; i < n; ++i) {
        unsigned p = props(M, s[i]);
        if ((p & P_UPPER) || (p & P_TITLE)) {
            if (previous_is_cased) return false;
            previous_is_cased = true; cased = true;
        } else if (p & P_LOWER) {
            if (!previous_is_cased) return false;
            previous_is_cased = true; cased = true;
        } else previous_is_cased = false;
    }
    return cased;
}

// ---- strings ----
__device__ __forceinline__ bool str_eq(const cp* a, int na, const cp* b, int nb) {
    if (na != nb) return false;
    for (int i = 0; i < na; ++i) if (a[i] != b[i]) return false;
    return true;
}
__device__ __forceinline__ u64 fnv_cp(const cp* s, int n) {
    u64 h = (u64)KS_FNV1A64_OFFSET_BASIS;
    for (int i = 0; i < n; ++i) { h ^= (u64)s[i]; h *= (u64)KS_FNV1A64_PRIME; }
    return h;
}
// Index of the key in a table, or -1.
__device__ int table_find(const HashTable& t, const cp* s, int n) {
    if (t.mask == 0) return -1;
    u64 h = fnv_cp(s, n);
    u64 i = h & t.mask;
    const u64* hashes = (const u64*)t.hashes;
    const int* lengths = (const int*)t.lengths;
    const i64* offsets = (const i64*)t.offsets;
    const cp* pool = (const cp*)t.pool;
    while (true) {
        int length = lengths[i];
        if (length < 0) return -1;
        if (hashes[i] == h && length == n && str_eq(pool + offsets[i], length, s, n))
            return ((const int*)t.values)[i];
        i = (i + 1) & t.mask;
    }
}

// ---- exact float sums ----
// CPython builtin sum() over floats (Neumaier), started from the integer 0.
struct Neumaier {
    double total = 0.0, compensation = 0.0;
    __device__ void add(double x) {
        double t = total + x;
        if (fabs(total) >= fabs(x)) compensation += (total - t) + x;
        else compensation += (x - t) + total;
        total = t;
    }
    __device__ double result() const {
        return (compensation != 0.0 && isfinite(compensation)) ? total + compensation : total;
    }
};
// CPython math.fsum (Shewchuk partials with half-even correction); finite inputs only. The partials
// do not overlap, so a double's exponent range bounds their number below the buffer's size.
__device__ double py_fsum(const double* values, int count) {
    double partials[KS_CONTEXT_ACTION_CUDA_FSUM_PARTIALS];
    int n = 0;
    for (int k = 0; k < count; ++k) {
        double x = values[k];
        int i = 0;
        for (int j = 0; j < n; ++j) {
            double y = partials[j];
            if (fabs(x) < fabs(y)) { double t = x; x = y; y = t; }
            double hi = x + y, yr = hi - x, lo = y - yr;
            if (lo != 0.0) partials[i++] = lo;
            x = hi;
        }
        n = i;
        if (x != 0.0) partials[n++] = x;
    }
    double hi = 0.0;
    if (n > 0) {
        double lo = 0.0;
        hi = partials[--n];
        while (n > 0) {
            double x = hi, y = partials[--n];
            hi = x + y;
            double yr = hi - x;
            lo = y - yr;
            if (lo != 0.0) break;
        }
        if (n > 0 && ((lo < 0.0 && partials[n - 1] < 0.0) || (lo > 0.0 && partials[n - 1] > 0.0))) {
            double y = lo * 2.0, x = hi + y, yr = x - hi;
            if (y == yr) hi = x;
        }
    }
    return hi;
}

// ---- row state: hunspell questions a row could not answer yet ----
struct Misses {
    int* count;              // number of recorded questions
    int capacity;
    cp* words;               // capacity x MAXS code points
    int* lengths;
    int* locales;
};
struct RowState {
    const Misses* misses;
    bool incomplete;         // a hunspell answer was missing: the row is redone once it is known
    bool fallback;           // the row needs the CPU path
};

// HunspellDictionary.check(normalized) through the answer table.
__device__ bool hunspell_check(const Model* M, int locale, const cp* word, int n, RowState* st) {
    int index = table_find(M->hunspell[locale], word, n);
    if (index >= 0) return ((const signed char*)M->hunspell_value[locale])[index] != 0;
    st->incomplete = true;
    const Misses* m = st->misses;
    if (m != nullptr && n <= MAXS) {
        int slot = atomicAdd(m->count, 1);
        if (slot < m->capacity) {
            for (int i = 0; i < n; ++i) m->words[(i64)slot * MAXS + i] = word[i];
            m->lengths[slot] = n;
            m->locales[slot] = locale;
        }
    }
    return false;
}

// ---- LanguageModel (language_model.py) ----
struct WordScore {
    double value; int known; i64 frequency; double gram_ratio; int exact; int spell_known;
    double ngram_score; double invalid_ratio; double raw_ngram_score;
};

// LanguageModel.normalize: casefold, keep letters, apostrophe and hyphen.
__device__ int lm_normalize(const Model* M, const cp* s, int n, cp* out) {
    int k = 0;
    for (int i = 0; i < n; ++i) {
        cp c = casefold(M, s[i]);
        if (is_alpha(M, c) || c == '\'' || c == '-') out[k++] = c;
    }
    return k;
}

// LanguageModel._raw_ngram_score
__device__ double lm_raw_ngram(const Model* M, int locale, const cp* word, int n) {
    cp padded[MAXS + 2];
    int k = lm_normalize(M, word, n, padded + 1);
    if (k == 0) return KS_LANGUAGE_MODEL_EMPTY_TOKEN_SCORE;
    padded[0] = '^';
    padded[k + 1] = '$';
    int length = k + 2;
    double scores[KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT];
    int m = 0;
    for (int o = 0; o < KS_LANGUAGE_MODEL_NGRAM_ORDERS_COUNT; ++o) {
        int order = (int)M->orders[o];
        int count = length - order + 1;
        if (count <= 0) continue;
        Neumaier sum;
        const double* logs = (const double*)M->gram_log[locale][o];
        for (int i = 0; i < count; ++i) {
            int index = table_find(M->grams[locale][o], padded + i, order);
            sum.add(index >= 0 ? logs[index] : M->unseen_log[locale][o]);
        }
        scores[m++] = sum.result() / (double)count;
    }
    return m ? py_fsum(scores, m) / (double)m : KS_LANGUAGE_MODEL_EMPTY_TOKEN_SCORE;
}

__device__ __forceinline__ double lm_ngram_score(const Model* M, int locale, const cp* word, int n) {
    return (lm_raw_ngram(M, locale, word, n) - M->ngram_mean[locale]) / M->ngram_deviation[locale];
}

// LanguageModel.score
__device__ WordScore lm_score(const Model* M, int locale, bool spelling, const cp* word, int n, RowState* st) {
    cp normalized[MAXS];
    int k = lm_normalize(M, word, n, normalized);
    if (k == 0) {
        WordScore empty = {KS_LANGUAGE_MODEL_EMPTY_TOKEN_SCORE, 0, 0, 0.0, 0, 0,
                           KS_LANGUAGE_MODEL_NATURALNESS_MIN, 1.0, KS_LANGUAGE_MODEL_NATURALNESS_MIN};
        return empty;
    }
    bool eligible = true;
    for (int i = 0; i < n; ++i) {
        cp c = word[i];
        if (!(is_alpha(M, c) || c == '\'' || c == '-')) { eligible = false; break; }
    }
    i64 frequency = 0;
    double popularity = 0.0;
    if (eligible) {
        int index = table_find(M->freq[locale], normalized, k);
        if (index >= 0) {
            frequency = ((const i64*)M->freq_count[locale])[index];
            popularity = ((const double*)M->popularity[locale])[index];
        }
    }
    bool exact = frequency != 0;
    bool spell_known = (spelling && eligible && str_isalpha(M, normalized, k))
        ? hunspell_check(M, locale, normalized, k, st) : false;
    bool known = exact || spell_known;
    // padded = f"^{normalized}$"; trigrams over it
    cp padded[MAXS + 2];
    padded[0] = '^';
    for (int i = 0; i < k; ++i) padded[i + 1] = normalized[i];
    padded[k + 1] = '$';
    int length = k + 2;
    int trigrams = length - (KS_LANGUAGE_MODEL_TRIGRAM_ORDER - 1);
    if (trigrams < 0) trigrams = 0;
    int hits = 0;
    for (int i = 0; i < trigrams; ++i)
        hits += table_find(M->grams[locale][1], padded + i, KS_LANGUAGE_MODEL_TRIGRAM_ORDER) >= 0;
    double ratio = trigrams ? (double)hits / (double)trigrams : 0.0;
    double invalid_ratio = 1.0 - ratio;
    double raw_naturalness = py_max(KS_LANGUAGE_MODEL_NATURALNESS_MIN,
                                    py_min(KS_LANGUAGE_MODEL_NATURALNESS_MAX, lm_ngram_score(M, locale, normalized, k)));
    double naturalness = raw_naturalness;
    double lexical = 0.0;
    if (exact) lexical = KS_LANGUAGE_MODEL_EXACT_WORD_BASE_SCORE + KS_LANGUAGE_MODEL_POPULARITY_WEIGHT * popularity;
    else if (spell_known) lexical = KS_LANGUAGE_MODEL_SPELL_KNOWN_SCORE;
    if (known) naturalness = py_max(naturalness, KS_LANGUAGE_MODEL_KNOWN_WORD_NATURALNESS_FLOOR);
    double value = lexical + KS_LANGUAGE_MODEL_NATURALNESS_WEIGHT * naturalness
                   - KS_LANGUAGE_MODEL_INVALID_RATIO_WEIGHT * invalid_ratio;
    WordScore result = {value, known, frequency, ratio, exact, spell_known, naturalness, invalid_ratio, raw_naturalness};
    return result;
}
