"""Minimal stub for the part of CuPy the context-v3 trainer's CUDA back end uses.

CuPy ships no type information. Device arrays are one class whose operations return device
arrays; `asnumpy` returns a host array of raw records, which the caller views or converts as the
dtype it expects.
"""

import numpy as np
import numpy.typing as npt
from numpy import bool_ as bool_
from numpy import float64 as float64
from numpy import int32 as int32
from numpy import int64 as int64
from numpy import uint8 as uint8
from numpy import uint32 as uint32
from numpy import uint64 as uint64

from . import cuda as cuda

class _Memory:
    ptr: int

class ndarray:
    data: _Memory
    def __len__(self) -> int: ...
    def __getitem__(self, key: object) -> ndarray: ...
    def __setitem__(self, key: object, value: object) -> None: ...
    def __eq__(self, other: object) -> ndarray: ...  # type: ignore[override]
    def __ne__(self, other: object) -> ndarray: ...  # type: ignore[override]
    def __invert__(self) -> ndarray: ...
    def __add__(self, other: object) -> ndarray: ...
    def __sub__(self, other: object) -> ndarray: ...
    def astype(self, dtype: object) -> ndarray: ...
    def fill(self, value: object) -> None: ...
    def reshape(self, *shape: int) -> ndarray: ...
    def sum(self) -> ndarray: ...

class RawKernel:
    def __call__(self, grid: tuple[int, ...], block: tuple[int, ...], args: tuple[object, ...]) -> None: ...

class RawModule:
    def __init__(self, *, code: str, options: tuple[str, ...] = ...) -> None: ...
    def get_function(self, name: str) -> RawKernel: ...

class _MemoryPool:
    def free_all_blocks(self) -> None: ...

def asarray(a: object, dtype: object = ...) -> ndarray: ...
def asnumpy(a: ndarray) -> npt.NDArray[np.void]: ...
def zeros(shape: int | tuple[int, ...], dtype: object = ...) -> ndarray: ...
def full(shape: int | tuple[int, ...], fill_value: object, dtype: object = ...) -> ndarray: ...
def arange(start: int, stop: int = ..., dtype: object = ...) -> ndarray: ...
def concatenate(arrays: list[ndarray]) -> ndarray: ...
def argsort(a: ndarray) -> ndarray: ...
def searchsorted(a: ndarray, v: ndarray, side: str = ...) -> ndarray: ...
def minimum(a: ndarray, b: object) -> ndarray: ...
def unique(a: ndarray, return_index: bool) -> tuple[ndarray, ndarray]: ...
def cumsum(a: ndarray) -> ndarray: ...
def any(a: ndarray) -> ndarray: ...
def all(a: ndarray) -> ndarray: ...
def get_default_memory_pool() -> _MemoryPool: ...
