"""Counts, sizes and lengths the tests expect or feed."""

from __future__ import annotations

from typing import Final

from keyswitch.constants.keyboard import LAYOUT_GROUP_COUNT
from keyswitch.constants.timing import FIELD_READER_RETRY_DELAYS_SECONDS
from keyswitch.constants.training import MINIMUM_SEQUENCE_DOCUMENTS_PER_GROUP
from keyswitch.constants.units import BYTES_PER_KIBIBYTE

CONTEXT_ACCESS_E2E_STAGE_COUNT: Final = 3
CONTEXT_ACCESS_E2E_PASSWORD_STAGE: Final = 2
CONTEXT_ACCESS_E2E_SELECTION_CHARACTERS: Final = 3
WINDOWS_E2E_DIAGNOSTIC_LOG_TAIL_LINES: Final = 30
WINDOWS_E2E_DIAGNOSTIC_LINE_CHARACTERS: Final = 600
WINDOWS_E2E_MAX_PROBE_ATTEMPTS: Final = 3
WINDOWS_E2E_FIRST_HISTORY_CHECK_ENTRIES: Final = 2
WINDOWS_E2E_SECOND_HISTORY_CHECK_ENTRIES: Final = 3
# Debug capture cap for the printed key-event sample.
X11_E2E_MAX_SAMPLE_EVENTS: Final = 12
# Generous bound on draining the engine's event queue; the real stopping condition (an empty queue)
# always fires first.
ACTION_BOUNDARY_MAX_FLUSH_ITERATIONS: Final = 1000
# "привет" has six letters, so retyping it erases "ghbdtn" with six Backspaces.
GHBDTN_REPLACEMENT_BACKSPACE_COUNT: Final = 6
# An arbitrary number of repeated (autorepeat) Enter presses.
ENTER_AUTOREPEAT_PRESS_COUNT: Final = 4
# Pinned expected results.
EPOCH_SELECTION_EXPECTED_NET_BENEFIT: Final = 3
EPOCH_SELECTION_EXPECTED_MINIMUM_NET_BENEFIT: Final = 2
EVIDENCE_LOAD_CALLS_AFTER_CONTENT_CHANGE: Final = 2
EVIDENCE_LOAD_CALLS_AFTER_MTIME_CHANGE: Final = 3
# Index of the boolean "segmentation is certain" element _completed_word returns.
COMPLETED_WORD_SEGMENTATION_CERTAIN_INDEX: Final = 2
# Number of keystrokes (word + trailing comma + space) the undo must erase.
UNDO_WORD_COMMA_SPACE_BACKSPACE_COUNT: Final = 3
OVERSIZED_BOUNDARY_POLICY_BYTES: Final = 65537
UIA_MULTIPLE_SELECTION_RANGE_COUNT: Final = 2
ATSPI_FIXTURE_CARET_OFFSET: Final = 8
ATSPI_FIXTURE_TEXT_CHARACTERS: Final = 10
ATSPI_FIXTURE_STALE_CARET_OFFSET: Final = 9
ATSPI_CACHE_PROBE_ATTEMPTS: Final = 2
READER_FACTORY_CALLS_AFTER_REOPEN: Final = 2
# documents() gives up finding all active splits after this many tries
SPLIT_DOCUMENT_SEARCH_MAX_ATTEMPTS: Final = 1000
# one row per surface token when misc-reconstructed
MISC_SPACING_ROW_COUNT: Final = 2
# aligned_text returns (text, spans, status)
ALIGNED_TEXT_STATUS_INDEX: Final = 2
# one document per split, joined by the shared physical family
LARGEST_COMPONENT_DOCUMENT_COUNT: Final = 4
# four documents, two tokens ("shared" + the split's word) each
GIANT_COMPONENT_ROW_COUNT: Final = 8
# the "shared" row from each of the four documents
GIANT_COMPONENT_QUARANTINED_ROW_COUNT: Final = 4
# freeze() caps for the small repeatability fixture corpus.
CORPUS_FIXTURE_FREEZE_MAX_DOCUMENTS: Final = 8
CORPUS_FIXTURE_FREEZE_MAX_SENTENCES_PER_DOCUMENT: Final = 8
# longer than CORPUS_BEFORE_WINDOW_CHARACTERS so the window clips instead of padding
CORPUS_WINDOW_LONG_PREFIX_CHARACTERS: Final = 120
# longer than CORPUS_AFTER_WINDOW_CHARACTERS so the window clips instead of padding
CORPUS_WINDOW_LONG_SUFFIX_CHARACTERS: Final = 100
# CORPUS_WINDOW_LONG_PREFIX_CHARACTERS "a"s plus one separating space
CORPUS_WINDOW_SAMPLE_TOKEN_START: Final = 121
# CORPUS_WINDOW_SAMPLE_TOKEN_START plus len("sample")
CORPUS_WINDOW_SAMPLE_TOKEN_END: Final = 127
# A document count large enough to force the "too many requested" guard.
HOLDOUT_OVER_DOCUMENT_LIMIT: Final = 2
# One selected sentence per source (M and U).
HOLDOUT_EXPECTED_SELECTED_SENTENCES: Final = 2
# The marked treebank fixture has two documents (doc-a, doc-b).
HOLDOUT_EXPECTED_TEST_DOCUMENTS: Final = 2
# Five fixture sid commands minus one excluded by the lexicon.
HOLDOUT_EXPECTED_SID_COMMANDS_OUTSIDE_LEXICON: Final = 4
HOLDOUT_EXPECTED_SID_TEST_ROWS: Final = 3
# Each of the arch/fedora/alpine fixtures declares three known commands and excludes one of them
# through the lexicon.
HOLDOUT_EXPECTED_COMMANDS_OUTSIDE_LEXICON: Final = 2
# Sentences generated for the holdout-assembly fixture corpus.
HOLDOUT_FIXTURE_SENTENCE_COUNT: Final = 40
# Sentences generated for the Tatoeba thinning fixture.
TATOEBA_FIXTURE_SENTENCE_COUNT: Final = 2000
# Loose bounds on how many of TATOEBA_FIXTURE_SENTENCE_COUNT survive thinning at
# TATOEBA_TEST_SAMPLE_PER_MILLE, generous enough not to be flaky.
TATOEBA_THINNING_MIN_EXPECTED_KEPT: Final = 120
TATOEBA_THINNING_MAX_EXPECTED_KEPT: Final = 280
# base and extra each contribute one row to the merged test membership.
MERGED_TEST_MEMBERSHIP_ROW_COUNT: Final = 2
# Repeats row_ids_sha256 to fabricate a duplicate membership entry.
DUPLICATED_ROW_IDS_FACTOR: Final = 2
# Wrong row count (the fixture actually streams one row) to trigger detection.
MERGE_FORGED_TRAIN_ROW_COUNT: Final = 2
ACTION_FEATURES_OVERSIZED_TEXT_CHARACTERS: Final = 100
ACTION_FEATURES_BEFORE_WHITESPACE_COUNT: Final = 3
ACTION_FEATURES_TAIL_DOT_COUNT: Final = 3
ACTION_FEATURES_LONG_TEXT_REPEATS: Final = 5000
ACTION_FEATURES_OVERSIZED_FIELD_REPEATS: Final = 500
ACTION_FEATURES_BEFORE_TEXT_BLOCK_CHARACTERS: Final = 300
ACTION_FEATURES_BEFORE_TEXT_TRAILING_SPACES: Final = 50
ACTION_FEATURES_SUBTEST_LABEL_CHARACTERS: Final = 10
ACTION_FEATURES_EXPECTED_COUNT_CEILING: Final = 3000
ACTION_FEATURES_EXPECTED_NAME_CHARACTERS_CEILING: Final = 160
ACTION_FEATURES_OVERSIZED_TEXT_VARIANT_INDEX: Final = 2
RECEIPT_CANDIDATE_RESTORED_ROWS: Final = 50
RECEIPT_FIXTURE_ROWS: Final = 128
# also "initially_correct" and "initially_wrong"
RECEIPT_IDENTIFIER_COUNT: Final = RECEIPT_FIXTURE_ROWS // 2
# rows per layout group; equals MINIMUM_SEQUENCE_DOCUMENTS_PER_GROUP, which the document-gate test
# relies on
RECEIPT_IDENTIFIERS_PER_GROUP: Final = RECEIPT_IDENTIFIER_COUNT // 2
RECEIPT_BASELINE_RESTORED_ROWS: Final = 48
# Calibration counts of the sealed-report fixture the evaluator and verifier tests build: per
# profile, then for the whole calibration split.
SEAL_FIXTURE_PROFILE_ROWS: Final = 20
SEAL_FIXTURE_PROFILE_CONVERT_ROWS: Final = 10
SEAL_FIXTURE_PROFILE_CONVERTED_CORRECTLY: Final = 9
SEAL_FIXTURE_PROFILE_CORRECT_CLASSES: Final = 19
SEAL_FIXTURE_CALIBRATION_ROWS: Final = 40
SEAL_FIXTURE_CALIBRATION_CONVERT_ROWS: Final = 20
SEAL_FIXTURE_CALIBRATION_CONVERTED_CORRECTLY: Final = 18
RECEIPT_ADDED_IDENTIFIER_COUNT: Final = 2
RECEIPT_MIXED_CASE_TRIMMED_LEFT: Final = 2
RECEIPT_INVALID_ERROR_VALUE: Final = 7
RECEIPT_INVALID_CARET_POSITION: Final = 999
RECEIPT_DUPLICATE_ENTRY_COUNT: Final = 2
SEQUENCE_INVALID_INTERVENTION_EVENT: Final = 999
DOCUMENT_SELECTION_ROWS_PER_DOCUMENT: Final = 3
DOCUMENT_SELECTION_FIXTURE_ROWS: Final = 420
RESTORATION_GATE_BASELINE_EXACTLY_RESTORED: Final = 4
RESTORATION_GATE_REDUCED_EXACTLY_RESTORED: Final = 3
RESTORATION_GATE_FURTHER_REDUCED_EXACTLY_RESTORED: Final = 2
BELOW_MINIMUM_SEQUENCE_DOCUMENTS_PER_GROUP: Final = MINIMUM_SEQUENCE_DOCUMENTS_PER_GROUP - 1
# The supported replay rows (the minimum rows per group in both groups) plus the one unsupported
# row.
SEQUENCE_SELECTED_ROWS_TOTAL: Final = MINIMUM_SEQUENCE_DOCUMENTS_PER_GROUP * LAYOUT_GROUP_COUNT + 1
# "hi there": eight physical keys, two completed words (see the test's own comment).
HI_THERE_KEY_COUNT: Final = 8
HI_THERE_COMPLETED_WORD_COUNT: Final = 2
SEQUENCE_TRIMMED_LEFT_CHARACTERS: Final = 8
SEQUENCE_TRIMMED_RIGHT_CHARACTERS: Final = 63
SEQUENCE_TRIM_LEFT_PADDING_WORD_REPEATS: Final = 43
SEQUENCE_TRIM_RIGHT_PADDING_LETTER_REPEATS: Final = 62
SEAL_FIXTURE_MISMATCHED_CALIBRATION_ROWS: Final = 41
SEQUENCE_LOAD_SPLIT_CALL_COUNT: Final = 2
SPAN_REAL_ENGINE_FAMILY_BUDGET: Final = 4
SPAN_EXPECTED_SEQUENCES: Final = 48
SPAN_SLASH_FAMILY_BUDGET: Final = 8
SPAN_EXPECTED_SKIPPED_INEXPRESSIBLE: Final = 12
SPAN_ODD_FAMILY_BUDGET: Final = 3
FEATURE_MASS_REPEAT_COUNT: Final = 2
FEATURE_MASS_COUNT_LIMIT: Final = 2
FEATURE_MASS_EXPANSION_COUNTS: Final = (3, 10, 1000)
FEATURE_MASS_CONTEXTS_LOOP_COUNT: Final = 4
FEATURE_MASS_GENEROUS_COUNT_LIMIT: Final = 10
# historical curriculum fixtures
HISTORICAL_CURRICULUM_EXPECTED_REDUCED_ROWS: Final = 3
HISTORICAL_CURRICULUM_RELABEL_SECOND_SOURCE_INDEX: Final = 2
HISTORICAL_CURRICULUM_COPY_COUNTS: Final = (1, 3, 9)
HISTORICAL_CURRICULUM_PAIR_SIZE: Final = 2
HISTORICAL_CURRICULUM_COVERAGE_SAMPLE_COUNT: Final = 256
HISTORICAL_CURRICULUM_TRIGGER_COVERAGE_SAMPLES: Final = 32
# select_rows fixtures
SELECT_ROWS_BUDGET: Final = 8
SELECT_ROWS_REPEATED_FAMILY_ROWS: Final = 12
SELECT_ROWS_DISTINCT_FAMILY_ROWS: Final = 8
CHOOSE_THRESHOLD_CONVERT_ROW_COUNT: Final = 100
CHOOSE_THRESHOLD_LOW_SCORING_TRUE_ROWS: Final = 4
CHOOSE_THRESHOLD_FALSE_ROW_COUNT: Final = 4
CHOOSE_THRESHOLD_LOW_SCORING_FALSE_ROWS: Final = 3
CHOOSE_THRESHOLD_GREEDY_NET_BENEFIT: Final = 96
CHOOSE_THRESHOLD_STRICT_NET_BENEFIT: Final = 95
CHOOSE_THRESHOLD_NET_BENEFIT_FLOOR: Final = 91
LEGACY_LOOKAHEAD_FAMILY_BUDGET: Final = 64
LEGACY_LOOKAHEAD_SEEDS_PER_FAMILY: Final = 128
LOOKAHEAD_PLANNED_VARIANTS_PER_SEED: Final = 2
LEGACY_LOOKAHEAD_EXPECTED_INPUT_SEEDS: Final = 2
LEGACY_LOOKAHEAD_EXPECTED_INPUT_ANCHORS: Final = 1
LEGACY_LOOKAHEAD_EXPECTED_PLANNED_CONVERT: Final = 1
LEGACY_LOOKAHEAD_EXPECTED_PLANNED_KEEP: Final = 1
# Pins training.IDENTIFIER_DROPOUT_FAMILIES: a change to the trainer's value must fail this test.
EXPECTED_IDENTIFIER_DROPOUT_FAMILIES: Final = 3
NATURAL_LOOKAHEAD_FAMILY_BUDGET: Final = 64
NATURAL_LOOKAHEAD_SEEDS_PER_FAMILY: Final = 32
# TransitionModel's own fixture rule: a token this short or shorter waits rather than converts,
# independent of the real model's logic.
TRANSITION_FIXTURE_PENDING_TOKEN_MAX_CHARACTERS: Final = 2
# More source records than CONTEXT_CORPUS_PER_GROUP_CAP allows, to see the cap and the
# order-independent tie-break both apply.
CONTEXT_CORPUS_FIXTURE_PHRASE_COUNT: Final = 20
CONTEXT_CORPUS_PER_GROUP_CAP: Final = 3
CONTEXT_FRAMES_PAIRED_ROW_STRIDE: Final = 2
LOOKAHEAD_CONFLICT_FRAME_COUNT: Final = 2
LOOKAHEAD_SAMPLING_FAMILY_BUDGET: Final = 2
LOOKAHEAD_SAMPLING_SEEDS_PER_FAMILY: Final = 2
LOOKAHEAD_SEEDS_PER_GENERATED_FAMILY: Final = 4
LOOKAHEAD_TOTAL_SEED_FIXTURES: Final = 12
CONTEXT_FILLER_CHARACTERS: Final = 700
# FieldContext keeps this many characters of the application name (frozen input_context.py, pending
# reseal).
FIELD_CONTEXT_APPLICATION_MAX_CHARACTERS: Final = 128
FIELD_CONTEXT_OVERLONG_NAME_CHARACTERS: Final = 200
FIELD_CONTEXT_OVERLONG_TEXT_CHARACTERS: Final = 900
# Confirmations a learned rule requires in the tests: the detection.learning_confirmations they
# configure, or the confirmations_required they pass to LearningStore.confirm_manual().
LEARNING_CONFIRMATIONS_REQUIRED: Final = 2
TECHNICAL_CORPUS_SPLIT_PROBE_COMMANDS: Final = 400
TECHNICAL_CORPUS_TYPO_VARIANT_PROBES: Final = 100
TECHNICAL_CORPUS_EXPECTED_KEPT_ROWS: Final = 2
TECHNICAL_CORPUS_EXPECTED_RESERVATION_PINS: Final = 2
TECHNICAL_CORPUS_EXPECTED_COMMAND_PROVENANCE: Final = 2
TECHNICAL_CORPUS_EXPECTED_SOURCE_VERIFICATION_PINS: Final = 3
CONTEXT_TRAINING_TEST_EPOCHS: Final = 2
CONTEXT_ACTION_REPLAY_COMMAND_COUNT: Final = 4
VERIFY_CALLS_DURING_REPLAY: Final = 2
CONTEXT_V2_EXPECTED_SOURCE_ROWS: Final = 64537
CONTEXT_V2_EXPECTED_RUSSIAN_SOURCE_ROWS: Final = 23034
CONTEXT_V2_EXPECTED_LEXICAL_CACHE_ROWS: Final = 148138
CONTEXT_V2_DUPLICATE_ROW_REPEATS: Final = 2
CONTEXT_V2_METRICS_TOTAL_ROWS: Final = 2
CONTEXT_V2_METRICS_INVALID_DESIRED_CONVERSIONS: Final = 3
CONTEXT_V2_METRICS_INVALID_CONVERTED_CORRECTLY: Final = 2
# The numeric report's frozen row count in this fixture.
CONTEXT_V2_HISTORY_REPORT_ROWS: Final = 2
# len(FEATURE_NAMES) * CONTEXT_ACTION_CLASS_COUNT weight coefficients
CONTEXT_V2_KERNEL_WEIGHT_COUNT: Final = 12
CONTEXT_V2_KERNEL_EPOCHS: Final = 4
CONTEXT_V2_KERNEL_COMPARISON_PLACES: Final = 14
CONTEXT_V2_EXPECTED_TEST_SAMPLES: Final = 2
CONTEXT_V2_WORSE_CONVERTED_CORRECTLY: Final = 499
CONTEXT_V2_WORSE_FALSE_CONVERSIONS: Final = 2
CONTEXT_V2_FEWER_CONVERTED_CORRECTLY: Final = 480
# matches len("tot ") / len("еще ")
WAIT_PAIR_CONTEXT_SUFFIX_CHARACTERS: Final = 4
# A detection.minimum_length a test configures instead of the default.
NON_DEFAULT_MINIMUM_WORD_LENGTH: Final = 5
CORE_MALFORMED_RULE_CONFIRMATIONS: Final = 3
CORE_EXPECTED_VALID_RULE_COUNT: Final = 2
# A history limit small enough that a test overflows it with a few entries.
HISTORY_LIMIT_FIXTURE: Final = 2
CORE_INJECTIONS_AFTER_SECOND_CORRECTION: Final = 2
CORE_INJECTIONS_AFTER_LEARNED_RULE_APPLIES: Final = 4
CORE_REPEATED_MANUAL_CONVERSIONS: Final = 2
# Index of the boundary event within an (strokes, target_group, boundary) injection tuple.
INJECTION_BOUNDARY_INDEX: Final = 2
# End offset of a one-character lookahead slice (`index + 1 : index + LOOKAHEAD_SLICE_END_OFFSET`).
LOOKAHEAD_SLICE_END_OFFSET: Final = 2
DETECTOR_OVERSIZED_MINIMUM_LENGTH: Final = 20
DETECTOR_RESCUE_INPUT_CALLS: Final = 3
# --- test_structural_token_protection --- One character past detector.is_protected_token's own
# `len(token) > 64` bound.
PROTECTED_TOKEN_OVERLENGTH_CHARACTERS: Final = 65
# --- EngineBranchTests fixtures ---
CLOSE_CALLS_AFTER_REPEATED_STOP: Final = 2
APPLICATION_CONTEXT_OVERFLOW_MARGIN: Final = 2
# A minimum length raised mid-test so a pending early switch is invalidated.
RAISED_EARLY_SWITCH_MIN_LENGTH: Final = 8
# Of EARLY_SWITCH_RU_WORD_FREQUENCIES, exactly привал/привет/приветствие start with "прив" (приз
# does not: its fourth letter differs).
PRIV_PREFIX_COMPLETIONS: Final = 3
# A .dic read bound too small to capture even the shortest stem, used to prove the read is truncated
# rather than silently unbounded.
DICTIONARY_TINY_READ_LIMIT_BYTES: Final = 4
# A policy tuned to switch on many ordinary-frequency completions rather than on one dominant one:
# low thresholds, and a dominance bar high enough that it is never crossed by this fixture data.
EARLY_SWITCH_POLICY_LOW_MINIMUM_COMPLETIONS: Final = 2
# Test-pinned expectations of the engine behaviour tests.
INJECTIONS_AFTER_QUOTE_PAUSE: Final = 2
SYMBOL_AND_WORD_STROKE_COUNT: Final = 6
REOPENED_WORD_CHARACTER_COUNT: Final = 6
INJECTIONS_AFTER_REOPENED_PAUSE: Final = 2
REPLAYED_STROKE_COUNT: Final = 6
REVERSED_CORRECTION_STROKE_COUNT: Final = 6
DIGIT_WORD_STROKE_COUNT: Final = 3
DISCARDED_WORD_LENGTH: Final = 2
INJECTIONS_AFTER_REPEATED_REJECTION: Final = 2
TOGGLE_REPEAT_COUNT: Final = 3
INJECTIONS_AFTER_TOGGLES: Final = 4
HELD_KEYS_DURING_INJECTION: Final = 2
LATE_KEYS_DURING_INJECTION: Final = 2
EARLY_SWITCH_PREFIX_STROKE_COUNT: Final = 4
EARLY_SWITCH_WORD_LENGTH: Final = 6
INJECTIONS_AFTER_LATE_STROKE: Final = 2
LATE_STROKE_INJECTION_LENGTH: Final = 5
INJECTIONS_AFTER_FAILED_LATE_STROKE: Final = 3
OVERSIZED_EARLY_SWITCH_MIN_LENGTH: Final = 40
INJECTIONS_AFTER_OVERRIDE: Final = 2
ROLLOVER_INJECTION_STROKE_COUNT: Final = 5
DROPPED_WORD_LENGTH: Final = 3
INJECTIONS_AFTER_UNDO_REVERT: Final = 2
INJECTIONS_AFTER_SECOND_EARLY_SWITCH: Final = 3
LEARNING_PROMPT_REQUIRED_CONFIRMATIONS: Final = 5
# A detection.learning_confirmations a test configures instead of the default.
NON_DEFAULT_LEARNING_CONFIRMATIONS: Final = 3
# A string setting value longer than LOGGED_SETTING_VALUE_MAX_CHARACTERS, so its logged form is
# shortened.
OVERSIZED_SETTING_STRING_CHARACTERS: Final = 100
HOTKEY_CHANGE_INDEX: Final = 2
# Unicode has exactly this many code points (U+0000 through U+10FFFF), spread across this many
# planes (0 through 16).
UNICODE_CODE_POINT_COUNT: Final = 0x110000
UNICODE_PLANE_COUNT: Final = 17
# Two nextafter() steps apart.
EXPECTED_ULP_DISTANCE: Final = 2
# Pinned shape of the packaged debian-trixie-commands-v1 resource.
PACKAGED_IDENTIFIER_COUNT: Final = 14160
# Bytes of filler used to build an oversized-looking resource file.
LEXICON_FILLER_BYTES: Final = 32
# A byte limit patched onto a resource loader (IDENTIFIER_LEXICON_MAX_BYTES,
# LEXICON_SUPPLEMENT_MAX_BYTES) to force its size refusal deterministically.
TINY_RESOURCE_LIMIT_BYTES: Final = 16
INPUT_DIAGNOSTICS_EXPECTED_EDIT_COUNT: Final = 2
INPUT_DIAGNOSTICS_FIRST_EDIT_CHARACTERS_BEFORE: Final = 2
# A generous bound on how many queued events one flush() may drain before it is fair to call the
# replay stuck rather than merely long.
SEQUENCE_MATRIX_MAX_FLUSH_ITERATIONS: Final = 100
INTENT_SHORT_TOKEN_CHARACTERS: Final = 8
INTENT_MEDIUM_TOKEN_CHARACTERS: Final = 12
INTENT_LONG_TOKEN_CHARACTERS: Final = 20
INTENT_GOLDEN_FEATURE_VALUE_COUNT: Final = 64
INTENT_GOLDEN_FINGERPRINT_COUNT: Final = 60
INTENT_MATRIX_TOKEN_LENGTHS: Final = (1, 4, 5, 7, 8, 11, 12, 19, 20)
# toggles source/target direction every other row
INTENT_MATRIX_DIRECTION_ALTERNATION_MODULUS: Final = 2
# A deterministic pseudo-random-looking weight pattern: index % modulus shifted and scaled into a
# small float range.
INTENT_RUNTIME_MATRIX_WEIGHT_MODULUS: Final = 17
INTENT_RUNTIME_MATRIX_WEIGHT_OFFSET: Final = 8
INTENT_DETERMINISTIC_WEIGHT_MODULUS: Final = 9
INTENT_DETERMINISTIC_WEIGHT_OFFSET: Final = 4
INTENT_METADATA_EXAMPLE_COUNT: Final = 1234
INTENT_EXPECTED_FINGERPRINT_COUNT: Final = 3
INTENT_TINY_FINGERPRINT_CAP: Final = 2
# Halving a length finds its middle item or character.
MIDPOINT_DIVISOR: Final = 2
INTENT_TINY_PAYLOAD_CAP_BYTES: Final = 32
# _validated_json_value() rejects metadata nested past depth 16 (not yet named there;
# PENDING_RESEAL); this goes comfortably past that.
INTENT_METADATA_NESTING_DEPTH_OVER_LIMIT: Final = 18
JSON_NESTING_OVERFLOW_DEPTH: Final = 1200
INTENT_LOADER_THREAD_POOL_WORKERS: Final = 2
INTENT_LOADER_EXPECTED_DECODE_CALLS: Final = 2
INTENT_DISCOVERY_SECOND_LOAD_CALL_COUNT: Final = 2
INTENT_DISCOVERY_THIRD_LOAD_CALL_COUNT: Final = 3
INTENT_DISCOVERY_EXPECTED_RELOAD_CALLS: Final = 2
# Twelve hashed files plus tools/environment_probe.py, certified since v21.
INTENT_STRICT_REPORT_VERIFIED_FILE_COUNT: Final = 13
STRICT_REPORT_SCRIPT_SEARCH_WINDOW_CHARACTERS: Final = 200
INTENT_DEFAULT_SAMPLES_PER_DIRECTION: Final = 10
INTENT_DEFAULT_POSITIVES_PER_DIRECTION: Final = 5
# Shared by the fixture-search helpers below, which brute-force short alphabetic strings until they
# land in a wanted split/collision.
INTENT_MINIMUM_SIGNATURE_LENGTH: Final = 3
# exclusive: try lengths INTENT_MINIMUM_SIGNATURE_LENGTH..8
INTENT_SIGNATURE_LENGTH_SEARCH_BOUND: Final = 9
# one more, so a deletion still leaves >= INTENT_MINIMUM_SIGNATURE_LENGTH
INTENT_MINIMUM_LENGTH_BEFORE_DELETION: Final = 4
INTENT_TYPO_AUGMENTATION_FIXTURE_LIMIT: Final = 3
INTENT_DATASET_MINIMUM_WORD_LENGTH: Final = 5
INTENT_DATASET_FUNCTION_MINIMUM_WORD_LENGTH: Final = 3
# How many rows a single identity collision contributes: one per layout direction, times one per
# trigger where a trigger multiplier applies.
INTENT_DATASET_DIRECTION_PAIR_COUNT: Final = 2
INTENT_DATASET_EXPECTED_PREPARED_WORD_COUNT: Final = 2
INTENT_DATASET_EXPECTED_STRESSED_EXAMPLE_COUNT: Final = 2
INTENT_DATASET_EXPECTED_CONTEXT_STRESS_PROFILE_COUNT: Final = 18
INTENT_DATASET_EXPECTED_HARD_NEGATIVE_SPLIT_ROWS: Final = {
        "train": 84_000,
        "development": 12_000,
        "calibration": 12_000,
        "threshold": 12_000,
        "test": 0,
    }
INTENT_DATASET_EXPECTED_HARD_NEGATIVE_SIGNATURE_COUNT: Final = 10_000
INTENT_DATASET_EXPECTED_HARD_NEGATIVE_WORDS_BY_GROUP: Final = {0: 5_000, 1: 5_000}
INTENT_DATASET_EXPECTED_HARD_NEGATIVE_ROLE_SIGNATURES: Final = {
        "train": 7_000,
        "development": 1_000,
        "calibration": 1_000,
        "threshold": 1_000,
        "test": 0,
    }
INTENT_DATASET_EXPECTED_MERGED_HARD_NEGATIVE_AUDITED_ROWS: Final = 120_000
INTENT_LEAKAGE_EXCLUDED_WORD_LENGTH: Final = 5
INTENT_LEAKAGE_INCLUDED_WORD_LENGTH: Final = 6
INTENT_LEAKAGE_RUSSIAN_WORD_SIGNATURE_LENGTH: Final = 7
# Every other fixture row is labelled positive.
INTENT_LABEL_PARITY_MODULUS: Final = 2
INTENT_LEAKAGE_PARALLEL_FEATURIZATION_EXAMPLE_COUNT: Final = 24
INTENT_LEAKAGE_PARALLEL_FEATURIZATION_WORKER_COUNT: Final = 2
INTENT_EXPECTED_AFFINITY_WORKER_COUNT: Final = 4
INTENT_EXCESSIVE_REQUESTED_WORKERS: Final = 99
INTENT_PERFECT_CONFUSION_COUNT: Final = 2
INTENT_OPTIMIZER_EXAMPLES_PER_DIRECTION_DIVISOR: Final = 2
INTENT_OPTIMIZER_POSITIVES_PER_DIRECTION_OVERRIDE: Final = 2
INTENT_OPTIMIZER_LABEL_VARIANT_COMBINATION_COUNT: Final = 4
INTENT_OPTIMIZER_CONTEXT_STRESS_SCORE_COUNT_PER_EXAMPLE: Final = 19
INTENT_OPTIMIZER_FEATURED_EXAMPLE_COUNT: Final = 30
INTENT_OPTIMIZER_DIRECTION_GROUP_MODULUS: Final = 4
INTENT_OPTIMIZER_DIRECTION_SWITCH_THRESHOLD: Final = 2
INTENT_OPTIMIZER_TRAINING_ROW_COUNT: Final = 20
INTENT_OPTIMIZER_PARALLEL_WORKER_COUNT: Final = 2
INTENT_OPTIMIZER_MAXIMUM_EPOCHS: Final = 2
INTENT_OPTIMIZER_PATIENCE: Final = 2
FTRL_CACHED_WEIGHTS_EPOCHS: Final = 5
INTENT_PLATT_TEST_MAX_ITERATIONS: Final = 100
INTENT_OPTIMIZER_SINGLE_EXAMPLE_MAX_ITERATIONS: Final = 10
INTENT_OPTIMIZER_EXPECTED_DIRECTIONAL_POSITIVE_COUNT: Final = 4
INTENT_OPTIMIZER_DIRECTIONAL_SAMPLE_DIRECTION_INDEX: Final = 2
INTENT_OPTIMIZER_NEGATIVE_FIXTURE_COUNT: Final = 10
INTENT_WEAK_SAMPLE_SIZE: Final = 1_000
INTENT_OPTIMIZER_NEGATIVE_TAIL_COUNT: Final = 10
INTENT_OPTIMIZER_SELECTION_FALSE_POSITIVE_BUDGET: Final = 10
INTENT_OPTIMIZER_FALSE_POSITIVE_BOUND_FALSE_POSITIVES: Final = 8
INTENT_OPTIMIZER_FALSE_POSITIVE_BOUND_TOTAL_NEGATIVES: Final = 17_220
INTENT_OPTIMIZER_COMPARISONS_PER_TRIGGER: Final = 2
INTENT_OPTIMIZER_DELETION_TYPO_STRONG_COUNT: Final = 90
INTENT_OPTIMIZER_DELETION_TYPO_WEAK_COUNT: Final = 10
INTENT_OPTIMIZER_IDENTITY_TYPO_STRONG_COUNT: Final = 9_410
INTENT_OPTIMIZER_IDENTITY_TYPO_WEAK_COUNT: Final = 490
INTENT_OPTIMIZER_EXPECTED_TRUE_POSITIVE_COUNT: Final = 2
INTENT_SAFETY_SAMPLE_MULTIPLIER: Final = 2
INTENT_VETO_SELECTION_SAMPLE_COUNT: Final = 100
INTENT_OPTIMIZER_INVALID_SELECTION_BUDGET: Final = 2
INTENT_EXTERNAL_MINIMUM_APPLICABLE_DELETION_LENGTH: Final = 5
INTENT_EXTERNAL_INVALID_AFFIX_BYTES_FLOAT: Final = 45.0
INTENT_EXTERNAL_UNDERSIZED_MINIMUM_WORDS_PER_GROUP: Final = 2
INTENT_EXTERNAL_SOURCE_KNOWN_SAMPLE_COUNT: Final = 2
INTENT_EXTERNAL_EXPECTED_NEGATIVE_ROWS: Final = 2
INTENT_EXTERNAL_SAFETY_TRIGGER_SAMPLE_COUNT: Final = 100
INTENT_EXTERNAL_THIRD_CANDIDATE_INDEX: Final = 2
INTENT_EXTERNAL_EXPECTED_SAFETY_POLICY_SAMPLES: Final = 2
INTENT_EXTERNAL_EXPECTED_HARD_GUARD_SAMPLES: Final = 4
INTENT_EXTERNAL_EXPECTED_HARD_GUARD_MODEL_EVALUATED: Final = 2
INTENT_EXTERNAL_UNKNOWN_TYPO_EXAMPLES_PER_TRIGGER: Final = 4
INTENT_EXTERNAL_UNKNOWN_TYPO_NEGATIVE_EXAMPLES_PER_TRIGGER: Final = 2
INTENT_EXTERNAL_EXPECTED_RAW_METRICS_COUNT: Final = 2
INTENT_EXTERNAL_EXPECTED_STRICT_SAMPLE_SIZE: Final = 5_000
INTENT_EXTERNAL_DICTIONARY_BYTES: Final = 123
INTENT_EXTERNAL_AFFIX_BYTES: Final = 45
INTENT_EXTERNAL_MINIMUM_WORDS_PER_GROUP: Final = 5000
INTENT_EXTERNAL_EXPECTED_COVERAGE_SAMPLE_COUNT: Final = 4
INTENT_EXTERNAL_EXPECTED_COVERAGE_PER_LABEL_COUNT: Final = 2
INTENT_PRESEALED_VERIFY_CALL_NUMBERS: Final = (1, 3)
INTENT_ARTIFACT_FULL_VERIFY_CALL_NUMBER: Final = 2
INTENT_ARTIFACT_PASSED_FULL_VERIFY_CALL_NUMBER: Final = 4
INTENT_ARTIFACT_EXPECTED_DIAGNOSTIC_COUNT: Final = 2
INTENT_CONCURRENT_CLAIMANTS: Final = 2
INTENT_ARTIFACT_SEALED_CANDIDATE_SAMPLES_PER_DIRECTION: Final = 100
INTENT_ARTIFACT_SEALED_CANDIDATE_POSITIVES_PER_DIRECTION: Final = 50
INTENT_TEST_TRAINING_SEED: Final = 17
INTENT_TAMPERED_TRAINING_SEED: Final = 18
INTENT_ARTIFACT_TAMPERED_VETOED_POSITIVE_SAMPLES: Final = 2
INTENT_PATCHED_MAX_SUPPORTED_FINGERPRINTS: Final = 2
INTENT_PATCHED_MAX_PAYLOAD_BYTES: Final = 512
INTENT_PATCHED_BYTE_LIMIT: Final = 4
INTENT_RUSSIAN_INPUT_INDEX: Final = 2
INTENT_LICENSE_INPUT_INDEX: Final = 3
INTENT_HARD_NEGATIVE_INPUT_INDEX: Final = 4
INTENT_ARTIFACT_QUANTIZATION_TEST_METRIC_COUNT: Final = 10
EXPECTED_INTENT_CONFIG_MINIMUM_WORD_LENGTH: Final = 5
EXPECTED_INTENT_CONFIG_MINIMUM_WORDS_PER_GROUP: Final = 5_000
EXPECTED_INTENT_PRODUCTION_ROLE_COUNTS: Final = {
        "train": 3_500,
        "development": 500,
        "calibration": 500,
        "threshold": 500,
        "test": 0,
    }
INTENT_MAX_PRESEAL_BYTES: Final = 64 * BYTES_PER_KIBIBYTE
EXPECTED_HARD_NEGATIVE_PRESEAL_SIGNATURE_COUNT: Final = 10_000
EXPECTED_PRESEAL_WORDS_BY_GROUP: Final = {"0": 5_000, "1": 5_000}
EXPECTED_PRESEAL_ROLE_WORDS_BY_GROUP: Final = {
        "train": {"0": 3_500, "1": 3_500},
        "development": {"0": 500, "1": 500},
        "calibration": {"0": 500, "1": 500},
        "threshold": {"0": 500, "1": 500},
    }
EXPECTED_PRESEAL_EXAMPLES_BY_ROLE: Final = {
        "train": 84_000,
        "development": 12_000,
        "calibration": 12_000,
        "threshold": 12_000,
    }
EXPECTED_SEALED_EXCLUSION_SIGNATURE_COUNT: Final = 288_843
EXPECTED_COMBINED_EXCLUSION_SIGNATURE_COUNT: Final = 298_843
WILSON_BOUND_TEST_SAMPLE_SIZE: Final = 1_000
WILSON_BOUND_COMPARISON_PLACES: Final = 8
WILSON_BOUND_TEST_FALSE_POSITIVES: Final = 2
INTENT_UNDERSIZED_CONFIG_MINIMUM_WORDS_PER_GROUP: Final = 4_999
FTRL_KERNEL_MAX_ROW_FEATURE_WIDTH: Final = 24
FTRL_KERNEL_POSITION_PARITY_MODULUS: Final = 2
FTRL_KERNEL_NATIVE_TEST_ROW_COUNT: Final = 3000
FTRL_KERNEL_NATIVE_TEST_SEED: Final = 11
FTRL_KERNEL_NATIVE_TEST_EPOCH_RANGE_END: Final = 5
FTRL_KERNEL_PARTIAL_ORDER_ROW_COUNT: Final = 800
FTRL_KERNEL_PARTIAL_ORDER_SEED: Final = 5
FTRL_KERNEL_PARTIAL_ORDER_SKIP_MODULUS: Final = 3
FTRL_KERNEL_DIVERGENCE_TEST_ROW_COUNT: Final = 600
FTRL_KERNEL_DIVERGENCE_TEST_SEED: Final = 3
FTRL_KERNEL_PACK_VALIDATION_ROW_COUNT: Final = 4
FTRL_KERNEL_EXPECTED_INDPTR_LENGTH: Final = 5
FTRL_KERNEL_COMPARISON_ROW_COUNT: Final = 1200
FTRL_KERNEL_COMPARISON_SEED: Final = 21
FTRL_KERNEL_COMPARISON_DEV_ROW_COUNT: Final = 300
FTRL_KERNEL_COMPARISON_DEV_SEED: Final = 22
FTRL_KERNEL_COMPARISON_MAX_EPOCHS: Final = 3
FTRL_KERNEL_FALLBACK_TEST_ROW_COUNT: Final = 200
FTRL_KERNEL_FALLBACK_TEST_SEED: Final = 31
FTRL_KERNEL_FALLBACK_TEST_DEV_ROW_COUNT: Final = 60
FTRL_KERNEL_FALLBACK_TEST_DEV_SEED: Final = 32
INTENT_ROW_SCORING_SECONDARY_LABEL_MODULUS: Final = 3
INTENT_ROW_SCORING_PARALLEL_TEST_WORKERS: Final = 3
INTENT_ROW_SCORING_CONTEXT_PROFILE_SAMPLE_COUNT: Final = 2
INTENT_ROW_SCORING_WIDE_PARALLEL_TEST_WORKERS: Final = 4
INTENT_ROW_SCORING_MODERATE_PARALLEL_TEST_WORKERS: Final = 2
INTENT_ROW_SCORING_EFFECTIVE_ROW_WORKERS_CAP: Final = 10
INTENT_ROW_SCORING_REQUESTED_ROW_WORKERS: Final = 8
INTENT_ROW_SCORING_AVAILABLE_ROW_WORKERS_CAP: Final = 3
INTENT_ROW_SCORING_MISORDERED_CHUNK_COUNT: Final = 2
LEARNING_PROMPT_FOCUSED_CARET_OFFSET: Final = 3
LEARNING_PROMPT_CHILD_COUNT_WITH_NULL_SLOT: Final = 2
LEARNING_PROMPT_DISMISS_CALLS_AFTER_ESCAPE_AND_STRAY_KEY: Final = 2
LEARNING_PROMPT_DISMISS_CALLS_AFTER_CLOSE_WITH_PROMPT: Final = 3
LEXICON_SUPPLEMENT_MINIMUM_SELECTION_COUNT: Final = 10
# Counts of native events a correction is expected to post.
MACOS_PRESS_RELEASE_EVENT_COUNT: Final = 2
MACOS_ERASE_EVENT_COUNT: Final = 4
MACOS_SHIFTED_KEYSTROKE_EVENT_COUNT: Final = 4
MACOS_BACKSPACE_PRESS_COUNT: Final = 2
# How many calls into post_inputs succeed before CountingAPI starts refusing.
MACOS_POST_INPUTS_CALLS_BEFORE_FAILURE: Final = 2
MACOS_CONTEXT_FIRST_WORD_CHARACTERS: Final = 6
MACOS_CONTEXT_TEXT_AREA_WORD_CHARACTERS: Final = 5
MACOS_CONTEXT_OVERSIZED_TEXT_MULTIPLIER: Final = 3
MACOS_CONTEXT_OUT_OF_BOUNDS_CARET_INDEX: Final = 99
MACOS_CONTEXT_NEGATIVE_RANGE_LENGTH: Final = -3
# keyswitch.tray_model.TrayActions has this many callback fields.
TRAY_ACTION_CALLBACK_COUNT: Final = 9
MACOS_CATALOG_EXPECTED_INSTALLED_COUNT: Final = 3
NAMED_VALUES_SAMPLE_UNNAMED_VALUE: Final = 12.5
NAMED_VALUES_SAMPLE_UNNAMED_LINE: Final = 2
# A floor the shipped production artifact (not the minimal() fixture) is expected to clear.
ORTHO_SHIPPED_MINIMUM_LENGTH_FLOOR: Final = 3
# Fixture invariants: the ud and technical origins are built so these counts hold everywhere they
# are asserted.
EXPOSURE_UNITS_PER_ORIGIN: Final = 2
EXPOSURE_MOVED_ROWS_PER_ORIGIN: Final = 3
EXPOSURE_TOTAL_MOVED_ROWS: Final = 6
EXPOSURE_PARENT_TEST_ROWS: Final = 8
EXPOSURE_FIXTURE_ROWS_PER_SPLIT: Final = 2
EXPOSURE_QUARANTINE_ROWS_AFTER_TRANSFER: Final = 8
EXPOSURE_QUARANTINE_GZIP_MEMBERS_AFTER_TRANSFER: Final = 3
EXPOSURE_REMAINING_ROWS_START_INDEX: Final = 2
EXPOSURE_TRUNCATED_GZIP_LINE_REPEATS: Final = 64
EXPOSURE_TRUNCATED_GZIP_TRAILING_BYTES: Final = 6
EXPOSURE_MISMATCHED_TRAIN_ROWS: Final = 9
PREFIX_CHARACTER_FEATURE_VALUE_CEILING: Final = 2
SUBTEST_PAYLOAD_PREVIEW_CHARACTERS: Final = 150
PREFIX_OVER_LENGTH_CAP_CHARACTERS: Final = 30
PREFIX_LONG_APPLICATION_NAME_REPEATS: Final = 100
# Trailing filler past PREFIX_MAX_CHARACTERS: must never surface in features.
PREFIX_TRAILING_FILLER_CHARACTERS: Final = 100
# Mirrors the frozen src/keyswitch/prefix_model.py before[-512:] context window.
PREFIX_MODEL_BEFORE_WINDOW_CHARACTERS: Final = 512
PREFIX_SPLIT_PROBE_SAMPLE_COUNT: Final = 1000
PREFIX_OUT_OF_RANGE_CONVERTED_COUNT: Final = 10**9
PREFIX_EXPECTED_CHARACTERS_BEFORE_CONVERSION: Final = 4
# A length below PREFIX_MIN_CHARACTERS, deliberately unsupported.
UNSUPPORTED_PREFIX_LENGTH: Final = 3
# Each pair holds exactly one correct and one wrong counterpart.
PREFIX_V2_PAIR_SIZE: Final = 2
# How many equal-weight duplicates a divided feature is split across.
PREFIX_V2_DUPLICATE_COPY_COUNTS: Final = (1, 3, 10, 1000)
# A features cap chosen to admit exactly two ranked features.
PREFIX_V2_NARROW_FEATURE_CAP: Final = 2
PROVENANCE_MINIMUM_HASHED_FILE_COUNT: Final = 30
READER_CALLS_AFTER_ONE_RETRY: Final = 2
# The initial call plus one retry per back-off delay.
READER_CALLS_AFTER_ALL_RETRIES: Final = 1 + len(FIELD_READER_RETRY_DELAYS_SECONDS)
READER_CALLS_AFTER_ONE_MORE_CAPPED_RETRY: Final = READER_CALLS_AFTER_ALL_RETRIES + 1
READER_CALLS_AFTER_REOPEN: Final = READER_CALLS_AFTER_ONE_MORE_CAPPED_RETRY + 1
READER_ATTEMPTS_AFTER_ONE_MORE_CAPPED_RETRY: Final = len(FIELD_READER_RETRY_DELAYS_SECONDS) + 1
# "стол" has this many letters; the reopened event reports the committed word.
STOL_REOPENED_WORD_CHARACTERS: Final = 4
NON_DEFAULT_HISTORY_LIMIT: Final = 50
HISTORY_BRANCH_ENTRY_COUNT: Final = 3
LEARNING_BROKEN_RULE_CONFIRMATIONS: Final = 2
LEARNING_SCALAR_RULE_VALUE: Final = 5
LEARNING_FULL_CONFIRMATIONS: Final = 5
LEARNING_MALFORMED_RULE_VALUE: Final = 9
LATIN_ALPHABET_SIZE: Final = 26
LANGUAGE_MODEL_CALIBRATION_WORD_LIMIT: Final = 12_000
LANGUAGE_MODEL_SCORE_CACHE_MAXSIZE: Final = 65_536
LANGUAGE_MODEL_BEST_DELETION_WORD_LENGTH: Final = 30
LANGUAGE_MODEL_BEST_DELETION_LIMIT: Final = 3
HUNSPELL_MAX_CHECK_CHARACTERS: Final = 128
TRAY_APP_EXPECTED_MENU_OPEN_CALLS: Final = 2
TRAY_APP_EXPECTED_CLOSE_CALLS: Final = 2
# Version, TextDirection, Status, IconThemePath.
DBUSMENU_PROPERTY_COUNT: Final = 4
# Index of the children list within a (id, properties, children) layout tuple.
DBUSMENU_LAYOUT_CHILDREN_INDEX: Final = 2
TRAY_APP_EXPECTED_PROPERTIES_UPDATED_CALLS: Final = 3
TRAY_APP_FAKE_HISTORY_LIMIT: Final = 25
TRAY_APP_PRESENT_CALLS_AFTER_ALL_PAGES: Final = 4
TRAY_APP_EXPECTED_QUIT_CALLS: Final = 2
TRAY_APP_EXPECTED_SCHEDULE_CALLS: Final = 2
TRAY_APP_EXPECTED_SYNC_AUTOSTART_CALLS: Final = 2
# one per theme tried: system, light, dark, invalid
EXPECTED_THEME_APPLY_CALLS: Final = 4
TRAY_APP_EXPECTED_SHOW_PROMPT_CALLS: Final = 2
TRAY_APP_PRESENT_CALLS_AFTER_REACTIVATE: Final = 2
TRAY_MENU_LAYOUT_HEADER_ENTRY_COUNT: Final = 2
TRAY_MENU_EXPECTED_SEPARATOR_COUNT: Final = 3
# opening state + set_layout + set_sound_enabled + set_indicator_style
TRAY_CONTROLLER_EXPECTED_DRAW_COUNT: Final = 4
GTK_EXPECTED_NAVIGATION_PAGE_COUNT: Final = 9
GTK_EXPECTED_HEADER_MENU_ITEM_COUNT: Final = 3
GTK_EXPECTED_APPLICATION_ROW_COUNT: Final = 3
GTK_SAMPLE_CONFIRMED_RULES: Final = 2
NON_DEFAULT_EARLY_SWITCH_MIN_LENGTH: Final = 3
GTK_EXPECTED_SAVE_HOTKEY_CALLS: Final = 2
GTK_EXPECTED_ADD_MANUAL_CALLS: Final = 2
GTK_MINIMUM_LENGTH_UPDATE: Final = 7
GTK_SAMPLE_CORRECTION_COUNT: Final = 5
RUSSIAN_PLURAL_SAMPLE_COUNTS: Final = (1, 2, 5, 11, 12, 24)
GTK_APPLICATION_ROW_COUNT_AFTER_UPDATE: Final = 2
# confirm_clear_history, confirm_clear_learning, confirm_reset
GTK_EXPECTED_DIALOG_PRESENT_CALLS: Final = 3
UPDATE_TINY_READ_LIMIT_BYTES: Final = 3
OVERSIZED_RELEASE_NOTES_CHARACTERS: Final = 5000
UPDATE_EXPECTED_DOWNLOAD_COUNT: Final = 2
# one SendInput call per distinct layout/boundary leg
WINDOWS_EXPECTED_SEND_BATCHES: Final = 2
WINDOWS_EXPECTED_HELD_COUNT: Final = 2
# two deleted characters, press+release each
WINDOWS_EXPECTED_BACKSPACE_EVENTS: Final = 4
WINDOWS_EXPECTED_DELIVERED_COUNT: Final = 2
# far past any real path limit
OVERLONG_PATH_CHARACTERS: Final = 5000
# how much of the (possibly huge) path to show
WINDOWS_SUBTEST_PATH_LABEL_CHARACTERS: Final = 12
# One press and one release for an unshifted key (including a backspace).
X11_EVENTS_PER_TAP: Final = 2
# Shift down, key down, key up, shift up.
X11_SHIFTED_TAP_EVENTS: Final = 2 * X11_EVENTS_PER_TAP
# Two backspace taps: deleting the old word plus a boundary/literal character.
X11_DELETE_TAP_EVENTS: Final = 2 * X11_EVENTS_PER_TAP
X11_EXCESSIVE_GROUP_COUNT: Final = 99
X11_LIBRARY_INIT_COUNT: Final = 2
X11_MIN_FREE_CALLS: Final = 2
# The range the Windows window offers for detection.early_switch_min_length.
EXPECTED_EARLY_SWITCH_MIN_LENGTH_SETTING_MIN: Final = 3
EXPECTED_EARLY_SWITCH_MIN_LENGTH_SETTING_MAX: Final = 8
# Lexical sources the auxiliary runtime evidence fingerprints.
EXPECTED_REFERENCE_LEXICAL_FILE_COUNT: Final = 6
# Values outside the range of every numeric setting, as a hand-edited settings file may hold.
SETTING_VALUE_ABOVE_EVERY_RANGE: Final = 100_000
SETTING_VALUE_BELOW_EVERY_RANGE: Final = -100_000
# Counts whose last digits pick each Russian noun form, teens included, for the russian_text tests.
RUSSIAN_QUANTITY_SAMPLE_COUNTS: Final = (1, 2, 5, 11, 12, 21, 22, 25, 111)
# A whole float is written without a fraction part; a fraction is written with a decimal comma.
RUSSIAN_QUANTITY_SAMPLE_WHOLE_FLOAT: Final = 3.0
RUSSIAN_QUANTITY_SAMPLE_FRACTION: Final = 2.5
